<?php


        ?>
        





<!DOCTYPE html>  
<html lang="fr">  
    <head>        
        <meta charset="UTF-8">  
        <title>Vue JS : Jour 2</title>  
        <link rel="preconnect" href="https://fonts.googleapis.com">  
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>  
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@100;300;400;500;600;700;800;900&display=swap" rel="stylesheet">  
        <link rel="stylesheet" href="style.css" />  
        <script type="module" src="index.js"></script>  
        
    </head>    
    <body id="app">  
          

          
    </body>
</html>