<?php
            $students = [
    [
        "firstName" => "James",
        "lastName" => "Fields",
        "grades" => [12, 11, 15],
        "average" => -1
    ],
    [
        "firstName" => "Richard",
        "lastName" => "Stein",
        "grades" => [18, 12, 13],
        "average" => -1
    ],
    [
        "firstName" => "Mark",
        "lastName" => "Hartoff",
        "grades" => [9, 11, 10],
        "average" => -1
    ],
    [
        "firstName" => "Thomas",
        "lastName" => "Nestle",
        "grades" => [9, 8, 5],
        "average" => -1
    ],
    [
        "firstName" => "Jeremy",
        "lastName" => "Brent",
        "grades" => [18, 15, 16],
        "average" => -1
    ]
];

$red ="red";
$orange ="orange";
$green ="green";

        function moyenne(array $tableau):float {
        
           
                 $total =0;
                 
                 
                        foreach($tableau as $grade){
                              $total += $grade;
            
           
            
                        }
                    $total = $total/count($tableau);     
            return $total;
                        }
            
         


        ?>
        





<!DOCTYPE html>  
<html lang="fr">  
    <head>        
        <meta charset="UTF-8">  
        <title>Vue JS : Jour 2</title>  
        <link rel="preconnect" href="https://fonts.googleapis.com">  
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>  
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@100;300;400;500;600;700;800;900&display=swap" rel="stylesheet">  
        <link rel="stylesheet" href="style.css" />  
        <script type="module" src="index.js"></script>  
        
    </head>    
    <body id="app">  
          

            
  
         <?php foreach($students as $student){ ?>
<article class="<?php  if(moyenne($student["grades"])<10){
echo $red;
}else if (moyenne($student["grades"])>= 10 && moyenne($student["grades"]) < 14){

echo $orange;
}else{
     echo $green;
}

 ?>">
    <header> 

  
        <h1> <?= "{$student["firstName"]}{$student["lastName"]}"?></h1>
     
       
    </header>
    <section>
        <h2>Notes : </h2>
        <ul>
            <?php foreach($student["grades"] as $grade){ ?>
           
            <li><?= "{$grade}";?></li>
            
            <?php  }; ?>  
        </ul>
    </section>
    <footer>
        <h3> <?php 
        
       echo moyenne($student["grades"])
           
            ?>  </h3>
    </footer>
</article>

<?php  }; ?>   
          
    </body>
</html>